version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd aws-crm
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync dist/ s3://crm-gia-le-stack-frontend-bucket --delete

artifacts:
  files:
    - '**/*'
  base-directory: aws-crm/dist
